In [1]:
import numpy as np
from sklearn.metrics import jaccard_score

evaluation_folder = '/home/cknuth/win2020/mobrob/catkin_ws/src/BKISemanticMapping/data/semantickitti_04/evaluations_ours/'

gt_all = np.array([])
pred_all = np.array([])
for i in range(60):
    if i % 10 == 0:
        print(i)
    
    result = np.loadtxt(evaluation_folder + str(i).zfill(6) + '.txt', dtype=np.uint32)
    gt = result[:,0]
    gt = gt & 0xFFFF
    pred = result[:,1]
    gt_all = np.concatenate((gt_all, gt))
    pred_all = np.concatenate((pred_all, pred))
    
    
gt_all_ours = gt_all
pred_all_ours = pred_all

classes_ours = np.unique(np.concatenate((gt_all_ours, pred_all_ours), axis=0))
scores_ours = jaccard_score(gt_all_ours, pred_all_ours, average=None)

# Ignore background and sky label
#pred_all = pred_all[gt_all != 0]
#gt_all = gt_all[gt_all != 0]
print(np.unique(np.concatenate((gt_all, pred_all), axis=0)) )
print(jaccard_score(gt_all, pred_all, average=None))

0
10
20
30
40
50
[ 0.  1.  5.  6.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[4.45297621e-02 3.12595244e-05 0.00000000e+00 0.00000000e+00
 3.14351180e-03 0.00000000e+00 5.23820749e-06 8.48254041e-03
 7.22861955e-06 7.30959679e-05 9.31913205e-04 4.40431623e-05
 6.31693552e-03 0.00000000e+00 0.00000000e+00]


0 & 4.453 \\
1 & 0.003126 \\
5 & 0.0 \\
6 & 0.0 \\
9 & 0.3144 \\
10 & 0.0 \\
11 & 0.0005238 \\
12 & 0.8483 \\
13 & 0.0007229 \\
14 & 0.00731 \\
15 & 0.09319 \\
16 & 0.004404 \\
17 & 0.6317 \\
18 & 0.0 \\


In [12]:
import numpy as np
from sklearn.metrics import jaccard_score

evaluation_folder = '/home/cknuth/win2020/mobrob/catkin_ws/src/BKISemanticMapping/data/semantickitti_04/evaluations_baseline/'

gt_all = np.array([])
pred_all = np.array([])
for i in range(60):
    if i % 10 == 0:
        print(i)
    
    result = np.loadtxt(evaluation_folder + str(i).zfill(6) + '.txt', dtype=np.uint32)
    gt = result[:,0]
    gt = gt & 0xFFFF
    pred = result[:,1]
    gt_all = np.concatenate((gt_all, gt))
    pred_all = np.concatenate((pred_all, pred))
    
gt_all_base = gt_all
pred_all_base = pred_all

classes_base = np.unique(np.concatenate((gt_all_base, pred_all_base), axis=0))
scores_base = jaccard_score(gt_all_base, pred_all_base, average=None)
    
print(np.unique(np.concatenate((gt_all, pred_all), axis=0)) )
print(jaccard_score(gt_all, pred_all, average=None))

0
10
20
30
40
50
[ 0.  1.  4.  5.  6.  7.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[4.45347438e-02 1.29181387e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 3.13001808e-03 0.00000000e+00
 0.00000000e+00 8.28367373e-03 7.28268469e-06 7.31087245e-05
 8.18289424e-04 4.46149728e-05 6.31691784e-03 0.00000000e+00
 0.00000000e+00]


In [22]:
scores_ours_ext = np.concatenate((scores_ours[0:2], np.array([0]), scores_ours[2:4], np.array([0]), scores_ours[4:]))

In [20]:
classes_ours

array([ 0.,  1.,  5.,  6.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.])

In [19]:
classes_base

array([ 0.,  1.,  4.,  5.,  6.,  7.,  9., 10., 11., 12., 13., 14., 15.,
       16., 17., 18., 19.])

In [26]:
for i in range(len(classes_base)):
    print('{:1g}'.format(classes_base[i]) + ' & ' \
          + '{:.3}'.format(100*scores_ours_ext[i]) + ' & ' \
          + '{:.3}'.format(100*scores_base[i]) + ' \\\\')

0 & 4.45 & 4.45 \\
1 & 0.00313 & 1.29 \\
4 & 0.0 & 0.0 \\
5 & 0.0 & 0.0 \\
6 & 0.0 & 0.0 \\
7 & 0.0 & 0.0 \\
9 & 0.314 & 0.313 \\
10 & 0.0 & 0.0 \\
11 & 0.000524 & 0.0 \\
12 & 0.848 & 0.828 \\
13 & 0.000723 & 0.000728 \\
14 & 0.00731 & 0.00731 \\
15 & 0.0932 & 0.0818 \\
16 & 0.0044 & 0.00446 \\
17 & 0.632 & 0.632 \\
18 & 0.0 & 0.0 \\
19 & 0.0 & 0.0 \\
