In [17]:
import numpy as np
from sklearn.metrics import jaccard_score

evaluation_folder = '/home/cknuth/win2020/mobrob/catkin_ws/src/BKISemanticMapping/data/semantickitti_04/evaluations_ours/'

gt_all = np.array([])
pred_all = np.array([])
for i in range(20):
    if i % 10 == 0:
        print(i)
    
    result = np.loadtxt(evaluation_folder + str(i).zfill(6) + '.txt', dtype=np.uint32)
    gt = result[:,0]
    gt = gt & 0xFFFF
    pred = result[:,1]
    gt_all = np.concatenate((gt_all, gt))
    pred_all = np.concatenate((pred_all, pred))
    
# Ignore background and sky label
pred_all = pred_all[gt_all != 0]
gt_all = gt_all[gt_all != 0]
    
print(np.unique(np.concatenate((gt_all, pred_all), axis=0)) )
print(jaccard_score(gt_all, pred_all, average=None))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[ 0.  1.  5.  6.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[0.00000000e+00 1.38840680e-03 0.00000000e+00 0.00000000e+00
 7.57453794e-03 0.00000000e+00 0.00000000e+00 9.88129015e-03
 1.89282807e-05 3.77804590e-04 5.27966419e-03 8.39771582e-05
 1.57724743e-02 0.00000000e+00 0.00000000e+00]


In [26]:
import numpy as np
from sklearn.metrics import jaccard_score

evaluation_folder = '/home/cknuth/win2020/mobrob/catkin_ws/src/BKISemanticMapping/data/semantickitti_04/evaluations_baseline/'

gt_all = np.array([])
pred_all = np.array([])
for i in range(20):
    if i % 10 == 0:
        print(i)
    
    result = np.loadtxt(evaluation_folder + str(i).zfill(6) + '.txt', dtype=np.uint32)
    gt = result[:,0]
    gt = gt & 0xFFFF
    pred = result[:,1]
    gt_all = np.concatenate((gt_all, gt))
    pred_all = np.concatenate((pred_all, pred))
    
# Ignore background and sky label
pred_all = pred_all[gt_all != 0]
gt_all = gt_all[gt_all != 0]
    
print(np.unique(np.concatenate((gt_all, pred_all), axis=0)) )
print(jaccard_score(gt_all, pred_all, average=None))

0
10
[ 0.  1.  4.  5.  6.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[0.00000000e+00 2.45263713e-02 0.00000000e+00 0.00000000e+00
 0.00000000e+00 7.54134013e-03 0.00000000e+00 0.00000000e+00
 9.69688820e-03 1.92830560e-05 3.78136397e-04 4.79734977e-03
 8.61103935e-05 1.57724743e-02 0.00000000e+00 0.00000000e+00]


In [23]:
result = np.loadtxt(evaluation_folder + str(99).zfill(6) + '.txt', dtype=np.uint32)
gt = result[:,0]
gt = gt & 0xFFFF
pred = result[:,1]

print(np.unique(np.concatenate((gt, pred), axis=0)) )
print(jaccard_score(gt, pred, average=None))

[ 0  1  9 11 13 14 15 16 17 18]
[0.01282031 0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]


In [25]:
a = np.array([1, 0, 0, 0])
b = np.array([1, 0, 1, 0])
jaccard_score(a, b, average=None)

array([0.66666667, 0.5       ])

In [12]:
np.unique(pred_all, axis=0)

array([ 0.,  1.,  5.,  9., 11., 12., 13., 14., 15., 16., 17., 18.])

In [13]:
np.unique(gt_all, axis=0)

array([ 1.,  5.,  6.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19.])